apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: app-of-apps
          image: 564131458637.dkr.ecr.ap-northeast-2.amazonaws.com/ub-ecr-repo
      imagePullSecrets:
        - name: ecr-regcred