apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
images:
- name: 564131458637.dkr.ecr.ap-northeast-2.amazonaws.com/ub-ecr-repo
  newName: 564131458637.dkr.ecr.ap-northeast-2.amazonaws.com/ub-ecr-repo
  newTag: 0f0890d1
resources:
- ../base
patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- service-patch.yaml
