apiVersion: v1
kind: Service
metadata:
  name: backend-active # active는 blue
  namespace: default
  labels:
    app: backend-active
spec:
  selector:
    app: istory-eks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080