apiVersion: v1
kind: Service
metadata:
  name: backend-preview # preview는 green
  namespace: default
  labels:
    app: backend-preview
spec:
  selector:
    app: istory-eks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080