#apiVersion: v1
#kind: Service
#metadata:
#  name: ub-svc
#  namespace: default
#spec:
#  selector:
#    app: istory-eks
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
#  type: NodePort
#  # type: LoadBalancer