repoURL: 'https://github.com/UBaRiAll/cicd.git'
apps:
  - name: kustomize
    project: default
    namespace: default
    source:
      path: kustomize
  # - name: demo
  #   project: default
  #   namespace: default
  #   source:
  #     path: demo
#  - name: sample-helm-1
#    project: default
#    namespace: default
#    source:
#      path: sample-helm-1


      # customValues: true
      # values:
      #   - values-eks.yaml
  # - name: prometheus
  #   project: default
  #   namespace: prom
  #   source:
  #     path: prometheus
  #     customValues: true
  #     values:
  #       - values-eks.yaml
  # - name: grafana
  #   project: default
  #   namespace: grafana
  #   source:
  #     path: grafana
  #     customValues: true
  #     values:
  #       - values-eks.yaml
  # - name: fluentbit
  #   project: default
  #   namespace: fluentbit
  #   source:
  #     path: fluent-bit
  #     customValues: true
  #     values:
  #       - values-eks.yaml
  # - name: aws-cli-batch
  #   project: default
  #   namespace: default
  #   source:
  #     path: aws-cli
  #     customValues: true
  #     values:
  #       - values-eks.yaml