#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: kustomize
#  namespace: argocd
#spec:
#  destination:
#    namespace: default
#    server: 'https://kubernetes.default.svc'
#  project: dev
#  source:
#    repoURL: https://github.com/UBaRiAll/k8s-manifest-repo.git
#    targetRevision: HEAD
#    path: kustomize/overlays
##    helm:
##      valueFiles:
##        - values.yaml
#  syncPolicy:
#    automated:
#      prune: true
#    syncOptions:
#      - Validate=false
#      - CreateNamespace=true
#      - PrunePropagationPolicy=background