apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - back-deploy.yaml
#  - service.yaml
#  - ingress.yaml


namePrefix: dev-
images:
  - name: 564131458637.dkr.ecr.ap-northeast-2.amazonaws.com/ub-ecr
    newName: 564131458637.dkr.ecr.ap-northeast-2.amazonaws.com/ub-ecr
    newTag: 29b15c16
resources:
  - ../../resources
